import { Function } from "../../interfaces";

import _toBe from "./toBe.json";
import _toBeCloseTo from "./toBeCloseTo.json";
import _toBeDefined from "./toBeDefined.json";
import _toBeFalsy from "./toBeFalsy.json";
import _toBeGreaterThan from "./toBeGreaterThan.json";
import _toBeGreaterThanOrEqual from "./toBeGreaterThanOrEqual.json";
import _toBeInfinity from "./toBeInfinity.json";
import _toBeInstanceOf from "./toBeInstanceOf.json";
import _toBeLessThan from "./toBeLessThan.json";
import _toBeLessThanOrEqual from "./toBeLessThanOrEqual.json";
import _toBeNaN from "./toBeNaN.json";
import _toBeTruthy from "./toBeTruthy.json";
import _toBeUndefined from "./toBeUndefined.json";
import _toContain from "./toContain.json";
import _toContainEqual from "./toContainEqual.json";
import _toEqual from "./toEqual.json";
import _toHaveBeenCalled from "./toHaveBeenCalled.json";
import _toHaveBeenCalledTimes from "./toHaveBeenCalledTimes.json";
import _toHaveBeenCalledWith from "./toHaveBeenCalledWith.json";
import _toHaveBeenLastCalledWith from "./toHaveBeenLastCalledWith.json";
import _toHaveBeenNthCalledWith from "./toHaveBeenNthCalledWith.json";
import _toHaveReturned from "./toHaveReturned.json";
import _toHaveReturnedTimes from "./toHaveReturnedTimes.json";
import _toHaveReturnedWith from "./toHaveReturnedWith.json";
import _toHaveLastReturnedWith from "./toHaveLastReturnedWith.json";
import _toHaveNthReturnedWith from "./toHaveNthReturnedWith.json";
import _toHaveLength from "./toHaveLength.json";
import _toMatch from "./toMatch.json";
import _toMatchObject from "./toMatchObject.json";
import _toThrow from "./toThrow.json";

export const toBe: Function = _toBe;
export const toBeCloseTo: Function = _toBeCloseTo;
export const toBeDefined: Function = _toBeDefined;
export const toBeFalsy: Function = _toBeFalsy;
export const toBeGreaterThan: Function = _toBeGreaterThan;
export const toBeGreaterThanOrEqual: Function = _toBeGreaterThanOrEqual;
export const toBeInfinity: Function = _toBeInfinity;
export const toBeInstanceOf: Function = _toBeInstanceOf;
export const toBeLessThan: Function = _toBeLessThan;
export const toBeLessThanOrEqual: Function = _toBeLessThanOrEqual;
export const toBeNaN: Function = _toBeNaN;
export const toBeTruthy: Function = _toBeTruthy;
export const toBeUndefined: Function = _toBeUndefined;
export const toContain: Function = _toContain;
export const toContainEqual: Function = _toContainEqual;
export const toEqual: Function = _toEqual;
export const toHaveBeenCalled: Function = _toHaveBeenCalled;
export const toHaveBeenCalledTimes: Function = _toHaveBeenCalledTimes;
export const toHaveBeenCalledWith: Function = _toHaveBeenCalledWith;
export const toHaveBeenLastCalledWith: Function = _toHaveBeenLastCalledWith;
export const toHaveBeenNthCalledWith: Function = _toHaveBeenNthCalledWith;
export const toHaveReturned: Function = _toHaveReturned;
export const toHaveReturnedTimes: Function = _toHaveReturnedTimes;
export const toHaveReturnedWith: Function = _toHaveReturnedWith;
export const toHaveLastReturnedWith: Function = _toHaveLastReturnedWith;
export const toHaveNthReturnedWith: Function = _toHaveNthReturnedWith;
export const toHaveLength: Function = _toHaveLength;
export const toMatch: Function = _toMatch;
export const toMatchObject: Function = _toMatchObject;
export const toThrow: Function = _toThrow;
