name: Lest
author: Total Anarchy Servers
description: Sets up and runs Lest on the current working directory

inputs:
  lua-version:
    description: Version of Lua to install if it is not already on PATH. See https://github.com/leafo/gh-actions-lua#luaversion
    required: false
    default: "5.4"
  lest-version:
    description: Version of Lest to install. See https://github.com/TAServers/lest/tags
    required: false
    default: latest
  args:
    description: Arguments that will be passed to the Lest CLI
    required: false
    default: ""
  skip-lua-install:
    description: Set this to true to skip installing Lua. This is useful if you already have Lua installed and on PATH in your pipeline
    required: false
    default: false

runs:
  using: composite
  steps:
    - uses: ilammy/msvc-dev-cmd@v1
      if: inputs.skip-lua-install != true

    - uses: leafo/gh-actions-lua@v10
      if: inputs.skip-lua-install != true
      with:
        luaVersion: ${{ inputs.lua-version }}

    - run: curl https://github.com/TAServers/lest/releases/download/${{ inputs.lest-version }}/lest.lua -o .lest/lest.lua

    - run: lua .lest/lest.lua ${{ inputs.args }}
