name: Deploy Site

on:
  push:
    branches:
      - master

jobs:
  site:
    uses: ./.github/workflows/site.yml

  deploy:
    needs: site

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v2
        id: deployment
