name: Lua CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        luaVersion:
          [
            "5.1.5",
            "5.2.4",
            "5.3.6",
            "5.4.4",
            "luajit-openresty",
            "luajit-2.0.5",
            "luajit-2.1.0-beta3",
          ]

    steps:
      - uses: actions/checkout@v3

      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: ${{ matrix.luaVersion }}

      - name: test
        run: lua lest.lua

  pre-release:
    runs-on: windows-latest
    needs: [lint, test]
    # if: github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == 'master'

    steps:
      - uses: actions/checkout@v3

      - uses: ilammy/msvc-dev-cmd@v1
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.4.4"

      - name: Install build dependencies
        run: |
          lua scripts/install.lua

      - name: Build release bundle
        run: |
          lua scripts/bundle.lua

      - run: |
          ls -la dist
          cat dist/lest.lua

      - name: Minify bundle
        run: |
          lua scripts/minify.lua

      - run: |
          ls -la dist
          cat dist/lest.lua

      # - uses: "marvinpinto/action-automatic-releases@latest"
      #   with:
      #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #     automatic_release_tag: "latest"
      #     prerelease: true
      #     title: "${{ github.event.head_commit.message }}"
      #     files: |
      #       dist/lest.lua

  release:
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: github.event_name == 'push' && github.ref_type == 'tag' && startsWith(github.ref_name, 'v')

    steps:
      - uses: actions/checkout@v3

      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.4.4"

      - name: Install build dependencies
        run: |
          lua scripts/install.lua

      - name: Build release bundle
        run: |
          lua scripts/bundle.lua
          lua scripts/minify.lua

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "Lest - ${{ github.ref_name }}"
          files: |
            dist/lest.lua
