name: LuaLS Annotations
on:
  push:
    branches:
      - master
jobs:
  deploy-annotations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - run: npm install
      - name: Build LuaLS-annotations
        run: npm run build:luals-annotations
      - name: Generate annotations
        run: npm run annotate:luals -- /tmp/annotations.lua
      - name: Checkout to new branch
        run: |
          git checkout luals-annotations || git checkout --orphan luals-annotations && git rm --cached -r .
      - name: Pull changes
        run: git pull origin luals-annotations
      - name: Copy annotations
        run: cp /tmp/annotations.lua .
      - name: Push annotations
        uses: EndBug/add-and-commit@v9
        with:
          add: "annotations.lua"
          default_author: github_actions
          message: "update annotations"
          new_branch: luals-annotations
