name: Release

on:
  push:
    branches:
      - master

jobs:
  lest:
    uses: ./.github/workflows/lest.yml

  release:
    runs-on: ubuntu-latest
    needs: lest

    permissions:
      id-token: write
      contents: write # This is needed to push tags

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: lest
          path: packages/lest/dist

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - name: Copy global readme to package
        run: cp README.md packages/lest/README.md

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v3
        id: publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: packages/lest
          provenance: true
          strategy: upgrade

      - name: Parse CHANGELOG.md
        uses: mindsers/changelog-reader-action@v2
        id: changelog
        if: steps.publish.outputs.type
        with:
          validation_level: warn
          version: ${{ steps.publish.outputs.version }}
          path: ./packages/lest/CHANGELOG.md

      - name: Push release
        uses: softprops/action-gh-release@v1
        if: steps.publish.outputs.type
        with:
          files: packages/lest/dist/lua/lest.lua
          tag_name: v${{ steps.publish.outputs.version }}
          name: Lest - v${{ steps.publish.outputs.version }}
          body: ${{ steps.changelog.outputs.changes }}

      - name: Update latest tag
        uses: EndBug/latest-tag@latest
        if: steps.publish.outputs.type

      - name: Push release for latest tag
        uses: softprops/action-gh-release@v1
        if: steps.publish.outputs.type
        with:
          files: packages/lest/dist/lua/lest.lua
          tag_name: latest
          name: Lest - ${{ steps.publish.outputs.version }}
          body: ${{ steps.changelog.outputs.changes }}
