name: Release

on:
  push:
    branches:
      - master

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml

  release:
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.4.4"

      - name: Install dependencies
        run: npm ci

      - name: Build release bundle
        run: npm run build
