name: Release

on:
  push:
    branches:
      - master

jobs:
  lua:
    uses: ./.github/workflows/lua.yml

  release:
    runs-on: ubuntu-latest
    needs: lua

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.4.4"

      - name: Install dependencies
        run: npm ci

      - name: Build release bundle
        run: npm run build:lua

      - name: Generate changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          output-file: "false"
          skip-commit: "true"
          skip-version-file: "true"
          git-path: "packages/lest"

      - name: Push release
        uses: softprops/action-gh-release@v1
        if: steps.changelog.outputs.skipped != 'true'
        with:
          files: packages/lest/dist/lest.lua
          tag_name: ${{ steps.changelog.outputs.tag }}
          name: Lest - ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

      - name: Update latest tag
        uses: EndBug/latest-tag@latest
        if: steps.changelog.outputs.skipped != 'true'

      - name: Push release for latest tag
        uses: softprops/action-gh-release@v1
        if: steps.changelog.outputs.skipped != 'true'
        with:
          files: packages/lest/dist/lest.lua
          tag_name: latest
          name: Lest - ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
