name: Release

on:
  push:
    branches:
      - master

jobs:
  lest:
    uses: ./.github/workflows/lest.yml

  release:
    runs-on: ubuntu-latest
    needs: lest

    permissions:
      id-token: write
      contents: write # This is needed to push tags

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: lest
          path: packages/lest/dist

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - name: Generate changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          output-file: "false"
          skip-commit: "true"
          skip-version-file: "true"
          git-path: "packages/lest"

      - name: Push release
        uses: softprops/action-gh-release@v1
        if: steps.changelog.outputs.skipped != 'true'
        with:
          files: packages/lest/dist/lua/lest.lua
          tag_name: ${{ steps.changelog.outputs.tag }}
          name: Lest - ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

      - name: Update latest tag
        uses: EndBug/latest-tag@latest
        if: steps.changelog.outputs.skipped != 'true'

      - name: Push release for latest tag
        uses: softprops/action-gh-release@v1
        if: steps.changelog.outputs.skipped != 'true'
        with:
          files: packages/lest/dist/lua/lest.lua
          tag_name: latest
          name: Lest - ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

      - name: Update package.json version
        if: steps.changelog.outputs.skipped != 'true'
        run: "sed -i 's/{{VERSION}}/${{ steps.changelog.outputs.tag }}/g' packages/lest/package.json"

      - name: Publish to NPM
        if: steps.changelog.outputs.skipped != 'true'
        working-directory: packages/lest
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
