name: Site - Test

on:
  push:
    paths:
      - site/**
      - docs/**
      - package.json
      - package-lock.json
      - .prettierrc
      - .github/workflows/**
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: cd site && npm ci

      - name: Build site
        run: npm run build:site

      - uses: actions/upload-pages-artifact@v1
        with:
          path: "site/build/"
